# Generated by Django 2.2.6 on 2019-10-18 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_category_measurements_quantity_recipe_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='food_category_name',
            new_name='name',
        ),
    ]
