# Generated by Django 2.2.6 on 2019-10-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20191018_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='picture_item',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_name',
        ),
    ]
